name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t sentiment-dashboard .

    - name: Run Container (Optional Smoke Test)
      run: |
        docker run -d -p 5000:5000 --name test-container sentiment-dashboard
        sleep 5  # give the container a few seconds to start
        curl --fail http://localhost:5000 || exit 1

    - name: Clean up
      if: always()
      run: |
        docker stop test-container || true
        docker rm test-container || true
